name: 'Hexo Build && Docker Image Build'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  hexo-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
      name: Use Node.js ${{ matrix.node-version }}
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: git submodule init && git submodule update
    - run: npm ci
    - run: npm run build --if-present
    - uses: actions/upload-artifact@v2
      with:
        name: hexo-build-output
        path: ./public

  docker-build:
    needs: ['hexo-build']
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Build the Docker image
    - uses: actions/download-artifact@v3
      with:
        name: hexo-build-output
        path: ./public
    - run: docker login ghcr.io -u hoony9x --password ${{ secrets.GITHUB_TOKEN }}
    - run: export TAG=$(date +%s) && docker build --tag ghcr.io/hoony9x/hoony9x.dev:$TAG . && docker push ghcr.io/hoony9x/hoony9x.dev:$TAG
